version: "3.9"

services:
  db:
    image: postgres
    container_name: poseidon_db
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - /home/md-sharif/docker_volumes/poseidon:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: poseidon

# Optional adminer
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"

volumes:
  poseidon:
