services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: sharif780/drinkwithme:latest
    container_name: drinkwithme_app
    profiles:
      - prod
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: 'production'

      DATABASE_URL: postgres://admin:admin@db:5432/drinkwithme
      AUTHSECRET: kjklsjfdkjksf
      CLOUDINARY_CLOUD_NAME: deskuwdew
      CLOUDINARY_API_KEY: 432538935528244
      CLOUDINARY_API_SECRET: UULVbMCsK_b0uMyWu4EIABgTUm4
      REDIS_CONNECTION_URL: redis://redis:6379
      STRIPE_SECRET_KEY: sk_test_51S14538ZZDvAakDbsGqbQDmg5wXzoTdkk2J1Nyob9EKQdnDBQQvAXA7pXp6ZMEAWapCy5zEbC8uv4sAbXRuWPB8X00nyy8JgHZ
      PORT: 3000

      FRONTEND_URL: https://drinkwithme.click
      BACKEND_URL: https://api.drinkwithme.click
      LIVE_BACKEND_URL: 'https://api.drinkwithme.click'

      ZOOM_CLIENT_ID: 7ugkZmTiSCCdzBQE6pjaUw
      ZOOM_CLIENT_SECRET: 8yWkiv3PyQOY2YCB8Bxnjow63St4NgJF
      ZOOM_ACCOUNT_ID: p79SDRYlRb-x1C3_WUK6yA
      ZOOM_API_BASE: https://api.zoom.us/v2

      # mail sender
      MAIL_USER: 'saifulislam106915@gmail.com'
      MAIL_PASS: 'lrftntftmlaofsqc'

      # Calendly
      CALENDLY_CLIENT_ID: 'fg55x-fzMMqJ1Zp9RBQIXraBhTuKv4KOOd9KkknALfw'
      CALENDLY_CLIENT_SECRET: 'IIIh5KMIGPJblQ_pyaRyY5UCUhwMqjeXYvYGBdIbPzw'
      CALENDLY_WEB_HOOK: '_S1geGz7RVmDmA9vSwZwjmKzmhAZbxN7t7i_zCE_2jw'

      CALENDLY_BASE_URL: 'https://api.calendly.com'

      CALENDLY_AUTH_URI: 'https://api.calendly.com/users/bc13fa22-2b30-4ca6-83f9-1b8df98a15ea'
      CALENDLY_ORG_URI: 'https://api.calendly.com/organizations/6626444f-1e7f-45d2-afa3-736ab90b6edd'

      CALENDLY_PERSONAL_ACCESS_TOKEN: 'eyJraWQiOiIxY2UxZTEzNjE3ZGNmNzY2YjNjZWJjY2Y4ZGM1YmFmYThhNjVlNjg0MDIzZjdjMzJiZTgzNDliMjM4MDEzNWI0IiwidHlwIjoiUEFUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJodHRwczovL2F1dGguY2FsZW5kbHkuY29tIiwiaWF0IjoxNzU5NjgzNDQ0LCJqdGkiOiI3MTk2MzU5Ni1hYWYxLTQyZDEtYTgyMi0xYzQxOTMyOTM1ZWUiLCJ1c2VyX3V1aWQiOiJiYzEzZmEyMi0yYjMwLTRjYTYtODNmOS0xYjhkZjk4YTE1ZWEifQ.EjGPl12c7gVls0XYbMHqytTgQ3xs91e4b0hL5gRLRhhtDxf9NfrFHLSti2TtYuQ357xrocsj-lW6fTcVW-1_2w'

    depends_on:
      - db
      - redis

  db:
    image: postgres:18.0-alpine3.22
    container_name: drinkwithme_db
    restart: always
    profiles:
      - prod
      - dev
      - db
    ports:
      - '5434:5432'
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: poseidon

  redis:
    image: redis:7.2
    container_name: my_redis
    restart: always
    profiles:
      - prod
      - dev
    ports:
      - '6379:6379'
    volumes:
      - redisData:/data

volumes:
  pgdata:
  redisData:
