# Use postgres/example user/password credentials

services:
  db:
    image: postgres
    container_name: poseidon_db
    restart: always
    ports:
      - ":5432:5432"
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - "poseidondb:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: poseidon

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
volumes:
  poseidondb:
