name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/poseidon_server:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/poseidon_server:latest

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker to VPS via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          docker compose down --remove-orphans
          docker compose rm -f
          docker compose pull
          docker compose up -d
          docker image prune -f
